const API = (window.THERMOLAG_API || '').replace(/\/$/, '');
let state = {scenario:'heatwave', data:null, selected:null, map:null, markers:{}, alerts:[]};
const $ = id => document.getElementById(id);
const tierClass = tier => tier === 'extreme' ? 'extreme' : tier === 'high' ? 'high' : tier === 'moderate' ? 'moderate' : 'low';
const tierColor = tier => ({low:'#2ed477',moderate:'#f1d24a',high:'#ff9c3d',extreme:'#ff5366'}[tier]||'#4c8dff');
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function api(path, options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw new Error(await r.text()||r.statusText);return r.headers.get('content-type')?.includes('xml')?r.text():r.json()}
function boot(msg){$('bootText').textContent=msg}
function hideBoot(){$('boot').classList.add('hide')}
function initMap(){state.map=L.map('map',{zoomControl:true,attributionControl:true}).setView([28.64,77.18],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(state.map)}
function markerIcon(tier,score){const c=tierColor(tier);return L.divIcon({className:'',html:`<div style="width:24px;height:24px;border-radius:50%;background:${c};border:3px solid rgba(255,255,255,.92);box-shadow:0 0 0 5px ${c}22,0 0 18px ${c}66;color:#07101c;font:800 8px Inter;display:grid;place-items:center">${Math.round(score)}</div>`,iconSize:[24,24],iconAnchor:[12,12]})}
function renderMarkers(){Object.values(state.markers).forEach(m=>m.remove());state.markers={};for(const w of state.data.wards){const d=w.current;const m=L.marker([w.lat,w.lng],{icon:markerIcon(d.risk.tier,d.risk.score)}).addTo(state.map);m.bindTooltip(`<b>${w.name}</b><br>${d.risk.tier_label} · ${d.risk.score}/100`,{direction:'top',offset:[0,-12]});m.on('click',()=>selectWard(w.id));state.markers[w.id]=m}}
function selectWard(id){const w=state.data.wards.find(x=>x.id===id);if(!w)return;state.selected=w;const d=w.current; $('wardTitle').textContent=w.name;$('riskScore').textContent=Math.round(d.risk.score);$('utci').textContent=d.utci.toFixed(1);$('wbgt').textContent=d.wbgt.toFixed(1);$('humidity').textContent=d.humidity;$('wind').textContent=d.wind_ms.toFixed(1);$('confidence').textContent=d.risk.confidence;$('riskCI').textContent=`CI ${d.risk.ci_low}–${d.risk.ci_high}`;$('reason').textContent=d.reason;$('vuln').textContent=Math.round(w.vulnerability_index*100)+'%';$('vulnBar').style.width=Math.round(w.vulnerability_index*100)+'%';$('vulnText').textContent=`${w.elderly_percent}% elderly · ${w.outdoor_workers_percent}% outdoor workers · ${w.cooling_centers} cooling centres`;
 const pill=$('tierPill');pill.className='pill '+tierClass(d.risk.tier);pill.textContent=d.risk.tier_label.toUpperCase();$('actionTier').className='pill '+tierClass(w.peak.risk.tier);$('actionTier').textContent=w.peak.risk.tier_label.toUpperCase();$('actionLead').textContent=`Peak ${w.peak.label} · ${w.peak.risk.score}/100`;$('actions').innerHTML=w.recommended_actions.map(x=>`<li>${x}</li>`).join('');renderForecast(w);}
function renderForecast(w){const days=w.days;const vals=days.map(d=>d.risk.score);const W=900,H=200,p=20;const min=0,max=100;const pts=vals.map((v,i)=>{const x=p+i*(W-2*p)/(vals.length-1);const y=H-p-(v-min)/(max-min)*(H-2*p);return [x,y]});const poly=pts.map(x=>x.join(',')).join(' ');const area=`${p},${H-p} ${poly} ${W-p},${H-p}`;let grid='';[0,25,50,75,100].forEach(v=>{const y=H-p-v/100*(H-2*p);grid+=`<line x1="${p}" x2="${W-p}" y1="${y}" y2="${y}" stroke="#17253a" stroke-width="1"/><text x="${W-3}" y="${y+3}" fill="#52627c" font-size="9" text-anchor="end">${v}</text>`});let circles=pts.map((pt,i)=>`<circle cx="${pt[0]}" cy="${pt[1]}" r="5" fill="${tierColor(days[i].risk.tier)}" stroke="#08111e" stroke-width="3"/>`).join('');$('forecastChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="riskFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#4c8dff" stop-opacity=".20"/><stop offset="1" stop-color="#4c8dff" stop-opacity="0"/></linearGradient></defs>${grid}<polygon points="${area}" fill="url(#riskFill)"/><polyline points="${poly}" fill="none" stroke="#4c8dff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${circles}</svg>`;$('forecastDays').innerHTML=days.map(d=>`<div class="day"><b>${d.label}</b><small>${d.risk.tier_label} risk</small><strong>${Math.round(d.risk.score)}</strong><div class="mini">UTCI ${d.utci}° · WBGT ${d.wbgt}°</div></div>`).join('')}
function renderAlerts(){if(!state.alerts.length){$('alertList').innerHTML='<div class="empty">No draft alerts yet. Select a high-risk ward and create one.</div>';return}$('alertList').innerHTML=state.alerts.map(a=>`<div class="alert-row"><div><b>${a.headline}</b><small>${a.id} · ${a.date}</small></div><div><span class="pill ${tierClass(a.tier)}">${a.tier_label.toUpperCase()}</span><small>${a.score}/100 · ${a.confidence}</small></div><div><small>${a.reason}</small></div><div class="alert-actions">${a.status==='pending_approval'?`<button class="approve" onclick="decideAlert('${a.id}',true)">Approve</button><button class="reject" onclick="decideAlert('${a.id}',false)">Reject</button>`:`<button onclick="viewCap('${a.id}')">CAP</button>`}</div></div>`).join('')}
async function refresh(){try{boot('Loading ward forecast…');const [data,alerts]=await Promise.all([api(`/api/dashboard?scenario=${state.scenario}`),api('/api/alerts')]);state.data=data;state.alerts=alerts.alerts;renderMarkers();if(!state.selected)selectWard(data.wards.find(w=>w.id==='W02')?.id||data.wards[0].id);else selectWard(state.selected.id);$('wardCount').textContent=data.summary.ward_count;$('highCount').textContent=data.summary.high_or_extreme_now;$('highSub').textContent=`${data.summary.extreme_now} Extreme now`;$('peakScore').textContent=Math.round(data.summary.peak_score);$('peakDate').textContent=`Peak ${data.summary.peak_date}`;const fresh=$('dataFreshness');if(fresh)fresh.innerHTML=`Forecast inputs: <strong>${state.scenario}</strong> demo scenario · refreshed ${new Date().toLocaleString()}`;$('alertCount').textContent=state.alerts.filter(a=>a.status==='pending_approval').length;renderAlerts();hideBoot();}catch(e){boot('API not reachable. Start backend locally or set config.js to the deployed API.');$('bootText').textContent=e.message}}
async function createDraft(){if(!state.selected)return toast('Select a ward first');const day=state.selected.current;try{const a=await api('/api/alerts/draft',{method:'POST',body:JSON.stringify({ward_id:state.selected.id,date:day.date,scenario:state.scenario})});state.alerts=[a,...state.alerts];$('alertCount').textContent=state.alerts.filter(x=>x.status==='pending_approval').length;renderAlerts();document.querySelector('#alerts').scrollIntoView();toast('Draft created — approval is required before release.')}catch(e){toast('Could not create alert')}}
async function decideAlert(id,approve){try{const a=await api(`/api/alerts/${id}/decision`,{method:'POST',body:JSON.stringify({approve,official:'SIH Demo Operator',note:approve?'Approved for prototype demonstration':'Rejected during prototype review'})});state.alerts=state.alerts.map(x=>x.id===id?a:x);$('alertCount').textContent=state.alerts.filter(x=>x.status==='pending_approval').length;renderAlerts();toast(approve?'Alert approved (simulated release).':'Alert rejected.')}catch(e){toast('Decision failed')}}
async function viewCap(id){try{const xml=await api(`/api/alerts/${id}/cap.xml`);const w=window.open('','_blank');w.document.write(`<pre style="white-space:pre-wrap;background:#07101b;color:#dbe8ff;padding:24px;font:13px monospace">${xml.replaceAll('&','&amp;').replaceAll('<','&lt;')}</pre>`);w.document.close()}catch(e){toast('CAP payload unavailable')}}
window.decideAlert=decideAlert;window.viewCap=viewCap;
$('scenario').addEventListener('change',e=>{state.scenario=e.target.value;state.selected=null;refresh()});$('refreshBtn').addEventListener('click',refresh);$('draftBtn').addEventListener('click',createDraft);$('centerBtn').addEventListener('click',()=>{if(state.selected)state.map.setView([state.selected.lat,state.selected.lng],13)});document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scroll)?.scrollIntoView()));
(async()=>{initMap();await refresh()})();
